name: 'Hello World'
description: 'Greet someone and record time'

inputs:
  who-to-greet:
    description: 'Who to greet'
    # type: string
    required: true
    default: 'World'
outputs:
  time:
  description: 'Time of greeting'
  runs: 
    using: 'node12'
    main: 'index.js'